version: '3.1'
services:
  nats:
    image: nats:1.0.6-linux
    restart: always
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    
  consul:
    image: consul:1.0.6
    restart: always
    ports:
      - 8500:8500
  
  prometheus:
    image: prom/prometheus:v2.2.1
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
     - 9090:9090

#   exporter:
#     image: prom/node-exporter:latest
#     ports:
#      - "9100:9100"
# #    network_mode: host
#   grafana:
#     image: grafana/grafana
#     ports:
#      - "3000:3000"
#     depends_on:
#       - prom
