version: '3.1'
services:
  db:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: webhook
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data