version: '3.1'
services:
  nats:
    image: nats:1.0.6-linux
    restart: always
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    
  consul:
    image: consul:1.0.6
    restart: always
    ports:
      - 8500:8500